#!/bin/tcsh
# $Revision$, $Date$
# $URL$

echo "Building in Code directory"; cd Code; make; cd ..
echo "Building in Integrators directory"; cd Integrators; make; cd ..
echo "Building in Example-Drivers directory"; cd Example-Drivers; make; cd ..
echo "Building in Tools directory"; cd Tools; make; cd ..
